version: "{build}"

image: Visual Studio 2015

environment:
  QT5_ROOT_DIRECTORY: C:\Qt\5.11.3
  HDF5_DIR: C:\Program Files\HDF_Group\HDF5\1.8.21\cmake
  PYTHON_HOME: C:\Python37

install:
  # Initialize thirdparty dependencies (remove with Conan integration)
  - git submodule update --init --recursive

  # Install build requirements
  - curl -fsS -O https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.21/bin/hdf5-1.8.21-Std-win7_64-vs14.zip
  - 7z x -bb0 hdf5-1.8.21-Std-win7_64-vs14.zip
  - msiexec /package hdf\HDF5-1.8.21-win64.msi /quiet
  - choco install doxygen.install
  - choco install wixtoolset
  - refreshenv

build_script:
  - mkdir _build
  - cd _build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DBUILD_PY_BINDING=ON -DBUILD_SAMPLES=ON -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build . --parallel --config Release
  - cmake --build . --target documentation_c
  - cmake --build . --target documentation_cpp
  - cpack -C Release
  - cmake --build . --target create_python_egg --config Release
