version: "{build}"

image: Visual Studio 2015

environment:
  QT5_ROOT_DIRECTORY: C:\Qt\5.11.3
  
clone_script:
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - choco install doxygen.install
  - choco install cmake
  - choco install wixtoolset
  - refreshenv
  
build_script:
  - set PATH="C:\Program Files\CMake\bin";%PATH%
  - build_win\win_make_all.bat
