dist: xenial

language: cpp
compiler: gcc

branches:
  only:
    - feature/add_conan_integration

addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - doxygen
      - graphviz
      - zlib1g-dev
      - qt5-default
      - libhdf5-dev
      - cmake
      - cmake-data

install:
  # Install conan
  - pip install --user conan
  - conan remote add -f kwc_bintray https://api.bintray.com/conan/kwc/conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

script:
  - mkdir _build
  - cd _build
  - conan install ..
  - /usr/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
  - make
  - /usr/bin/cpack -G DEB
