image: Visual Studio 2015

environment:
  QT5_ROOT_DIRECTORY: C:\Qt\5.11.3
  
clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
  - choco install doxygen.install
  
build_script:
  - build_win\win_make_cmake.bat v140
  - build_win\win_make_build.bat
  
