name: Build macOS

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-13

    steps:
      # XProtect can cause random failures if it decides that the DMG we create
      # during the packaging phase is malware.
      # See https://github.com/actions/runner-images/issues/7522 and https://github.com/servo/servo/pull/30779
    - name: Kill XProtectBehaviorService
      run: |
          echo Killing XProtect.; sudo pkill -9 XProtect >/dev/null || true;

    - name: Downgrade Python version
      uses: actions/setup-python@v4
      id: cp39
      with:
        python-version: '3.9'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        setup-python: false
        version: '5.15.2'
        target: 'desktop'

    - name: Install Dependencies
      run: brew install ninja doxygen graphviz protobuf hdf5@1.10 pkg-config

    - name: Install Cap’n Proto
      run: |
        mkdir "${{ runner.workspace }}/capnp"
        cd "${{ runner.workspace }}/capnp"
        curl -O https://capnproto.org/capnproto-c++-0.9.0.tar.gz
        tar zxf capnproto-c++-0.9.0.tar.gz
        cd capnproto-c++-0.9.0
        ./configure
        make -j
        sudo make install

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules:  'true'
        fetch-depth: 0

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
        
    - name: Install Python requirements
      run: |
        sudo pip3 install -r "$GITHUB_WORKSPACE/doc/requirements.txt"

    - name: CMake
      run: |
        mkdir "${{ runner.workspace }}/_build"
        cd "${{ runner.workspace }}/_build"
        cmake $GITHUB_WORKSPACE -G "Ninja" \
        -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/submodule_dependencies.cmake \
        -DHAS_HDF5=ON \
        -DHAS_QT5=ON \
        -DHAS_CURL=ON \
        -DHAS_CAPNPROTO=ON \
        -DHAS_FTXUI=ON \
        -DBUILD_DOCS=ON \
        -DBUILD_APPS=ON \
        -DBUILD_SAMPLES=ON \
        -DBUILD_TIME=ON \
        -DBUILD_PY_BINDING=ON \
        -DBUILD_CSHARP_BINDING=OFF \
        -DBUILD_ECAL_TESTS=ON \
        -DECAL_INCLUDE_PY_SAMPLES=OFF \
        -DECAL_INSTALL_SAMPLE_SOURCES=ON \
        -DECAL_JOIN_MULTICAST_TWICE=OFF \
        -DECAL_NPCAP_SUPPORT=OFF \
        -DECAL_THIRDPARTY_BUILD_CMAKE_FUNCTIONS=ON \
        -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF \
        -DECAL_THIRDPARTY_BUILD_SPDLOG=ON \
        -DECAL_THIRDPARTY_BUILD_TINYXML2=ON \
        -DECAL_THIRDPARTY_BUILD_FINEFTP=ON \
        -DECAL_THIRDPARTY_BUILD_CURL=OFF \
        -DECAL_THIRDPARTY_BUILD_GTEST=ON \
        -DECAL_THIRDPARTY_BUILD_HDF5=OFF \
        -DECAL_THIRDPARTY_BUILD_RECYCLE=ON \
        -DECAL_THIRDPARTY_BUILD_TCP_PUBSUB=ON \
        -DECAL_THIRDPARTY_BUILD_QWT=ON \
        -DECAL_THIRDPARTY_BUILD_YAML-CPP=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH=/usr/local/opt/hdf5@1.10 \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON \
        -DPython_FIND_STRATEGY=LOCATION \
        -DPython_FIND_REGISTRY=NEVER
        sudo mkdir /etc/ecal
        sudo cp "$GITHUB_WORKSPACE/ecal/core/cfg/ecal.ini" /etc/ecal
      shell: bash

    - name: Build Release
      run: cmake --build . --config Release
      working-directory: ${{ runner.workspace }}/_build

#    - name: Build Documentation C
#      run: cmake --build . --target documentation_c
#      working-directory: ${{ runner.workspace }}/_build

#    - name: Build Documentation C++
#      run: cmake --build . --target documentation_cpp
#      working-directory: ${{ runner.workspace }}/_build

#    currently event test fails under macos ..
#    - name: Run Tests
#      run: ctest -V
#      working-directory: ${{ runner.workspace }}/_build

    - name: Pack
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 3
        command: cd ${{ runner.workspace }}/_build && cpack -G DragNDrop 

    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: ${{ runner.workspace }}/_build/_deploy/*.dmg
