name: Build with CMake

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      #run: brew install zlib1g-dev python3.6-dev python3-pip python3-setuptools libcurl4-openssl-dev
      run: brew install doxygen graphviz qt5 hdf5 protobuf
