name: Build with CMake

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Install Dependencies
      #run: brew install doxygen graphviz zlib1g-dev qt5-default libhdf5-dev python3.6-dev python3-pip python3-setuptools libcurl4-openssl-dev libprotobuf-dev libprotoc-dev protobuf-compiler
      run: brew install doxygen
