name: Cherry-pick to support branches

on:
  push:
    branches:
      - master

# on:
#   pull_request:
#     branches:
#       - master
#     types: ["closed"]

jobs:
#   cherry_pick_v_5_12:
#     runs-on: ubuntu-latest
#     name: Cherry pick into support/v5.12
#     if: ${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick-v5.12') && github.event.pull_request.merged == true }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: Cherry pick into support/v5.12
#         uses: carloscastrojumo/github-cherry-pick-action@v1.0.9
#         with:
#           branch: support/v5.12
#           labels: |
#             cherry-pick
#           title: '[cherry-pick] {old_title}'
#           body: 'Cherry picking #{old_pull_request_id} onto this branch'


  # Create an empty PR, if the cherry_pick_v_5_12 job has failed
  empty_pr_v5_12:
    runs-on: ubuntu-latest
    # needs: cherry_pick_v_5_12
    # if: ${{ failure() }}

    steps:

      # Checkout the repository and switch to the support/v5.12 branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: support/v5.12

      # Create a new branch from the support/v5.12 branch and commit an empty commit
      - uses: EndBug/add-and-commit@v9
        with:
          commit: --allow-empty
          message: 'cherry-pick: empty commit'
          new_branch: empty-pr-branch

      - name: Create empty PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'cherry-pick: empty PR'
          title: 'cherry-pick: empty PR'
          body: 'This PR was created automatically to indicate that the cherry-pick to support/v5.12 failed.'
#          branch: empty-pr-branch
          base: support/v5.12
          draft: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
