name: Display merged commits

on:
  pull_request:
    branches:
      - master
    types: ["closed"]

jobs:
  
  display-commits:
    runs-on: ubuntu-latest
    name: Display commits this PR has created

    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: display merge commit sha
        run: echo "The merge commit sha is ${{ github.event.pull_request.merge_commit_sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
