name: Display merged commits

on:
  pull_request:
    branches:
      - master
    types: ["closed"]

jobs:
  
  display-commits:
    runs-on: ubuntu-latest
    name: Display commits this PR has created

    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get the PR number
        id: pr_number
        run: echo "PR_NUMBER=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Get the PR commits
        id: pr_commits
        run: |
          git fetch origin +refs/pull/${{ steps.pr_number.outputs.PR_NUMBER }}/merge
          git log --pretty=format:"%h - %s" FETCH_HEAD..HEAD > pr_commits.txt
          echo "::set-output name=commits::$(cat pr_commits.txt)"

      - name: Display the PR commits
        run: echo "${{ steps.pr_commits.outputs.commits }}"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
